### ISSUE TITLE
Missing dependency headers in map files

### ISSUE THREAD

**Issue by AppliedNav** [billvaglienti/ProtoGen#90]
When Protogen builds a map file, it fails to include dependency headers, if, for example, a packet in one source file depends on a structure in another file.

**Comment by billvaglienti** [comment]
Fixed in 2.18

**Comment by AppliedNav** [comment]
For some reason, this issue persists after 2.18 update... we should take another look at it.

**Comment by AppliedNav** [comment]
OK, I see what's happening (sort of). The code change you made in 2.18 redundantly adds dependency header includes for data types, but the actual issue I was reporting is not addressed. The missing dependencies I was referring to were the map headers for the independent data, which contain prototypes to the C++ functions that do the mapping/unmapping of the independent data types used.

**Comment by AppliedNav** [comment]
Should I create a new issue or you want to reopen this one ?

**Comment by billvaglienti** [comment]
I need an example that shows this failing. Send me your xml so I can figure
it out.

Bill Vaglienti
541 399 7883
4207 Post Canyon
Hood River OR, 97031
